### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by HachemBouhadede** [202306-NEA-DZ-FEW/team-nine-capstone#4]
this will be the component responsible for loggin in and out the user, it is possible to reach by 2 to 3 ways

- [x] Initiate Firebase

- [x]  Firebase authentication

- [ ] pop up form when reached - (in case of trouble with pop switch to re-route to an authentication page)

- [x] create sign up form

- [x] create sign in form

- [ ] user context 

![image](https://github.com/202306-NEA-DZ-FEW/team-nine-capstone/assets/137968168/6b976cd0-7f9c-459a-9212-d557b7af5993)

![image](https://github.com/202306-NEA-DZ-FEW/team-nine-capstone/assets/137968168/87ee9b3c-a45d-4ec8-9e67-4cdf8d4a9685)

- [ ] add sign out option and other user options when user = true

![image](https://github.com/202306-NEA-DZ-FEW/team-nine-capstone/assets/137968168/19b3f1ac-5176-4eca-a0f7-7cdc1f953314)

**Comment by Khalil-NOUI** [comment]
unmarked issues are to be re declared later on

**Comment by HachemBouhadede** [comment]
user contrext will dealt with in user context issue
