### ISSUE TITLE
Enhance styling of Herosection and Event create & edit page

### ISSUE THREAD

**Issue by Khalil-NOUI** [202306-NEA-DZ-FEW/team-nine-capstone#70]
**Task title**
Improve HomePage & Enhance Create Event And Edit Event page styling

**Task description**
provide updated hereSection and Enhance Create Event And Edit Event page

**Subtasks**
- enhance Hero Section
-Enhance Create Event And Edit Event page styling

**Comment by HachemBouhadede** [comment]
mm @Khalil-NOUI i dunno how, but the commits here went straight to develope ! and the preview has the old version of the recently updated version !

**Comment by Khalil-NOUI** [comment]
@HachemBouhadede. 
I checked the develop branch code and it's not similar to whats in here !
or perhaps i misunderstood you , can you please explain more ??

**Comment by HachemBouhadede** [comment]
> @HachemBouhadede I checked the develop branch code and it's not similar to whats in here ! or perhaps i misunderstood you , can you please explain more ??

was a mistake on my side
